apiVersion: apps/v1
kind: Deployment
metadata:
  name: department
  namespace: default
  labels:
    app: department
spec:
  selector:
    matchLabels:
      app: department
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: department
    spec:
      containers:
        - name: department
          image: jitendra111/department-service:0.0.1
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1024Mi
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 90
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 90
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 30
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: cluster-config-map
                  key: mysql-database-host
            - name: DEPARTMENT_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: cluster-config-map
                  key: department-database-name
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: cluster-config-map
                  key: mysql-database-port
            - name: MYSQL_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cluster-secret
                  key: mysql-root-username
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cluster-secret
                  key: mysql-root-password
          ports:
            - containerPort: 8085
              name: department
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: department-svc
  namespace: default
spec:
  selector:
    app: department
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: department-svc
      protocol: TCP
      port: 80
      targetPort: 8085

---
apiVersion: v1
kind: Service
metadata:
  name: department-1b
  namespace: default
spec:
  selector:
    app: department
  type: LoadBalancer
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: department
      protocol: TCP
      port: 80
      targetPort: 8085